# EXPERIMENT PARAMS
"NUM_SEEDS": 1
"SEED": 1

# WANDB PARAMS
"PROJECT": "overcooked"

"ALG_NAME": 'iql'

# RUN PARAMS
"NUM_ENVS": 32
"NUM_STEPS": 256
"TOTAL_TIMESTEPS": 10e7
"VERBOSE": FALSE
"WANDB_ONLINE_REPORT": TRUE
"NUM_TEST_EPISODES": 32
"TEST_INTERVAL": 50000

# NEURAL NET PARAMS
"AGENT_HIDDEN_DIM": 64
"AGENT_INIT_SCALE": 2.
"PARAMETERS_SHARING": FALSE

# ALGO PARAMS
"BUFFER_SIZE": 5000
"BUFFER_BATCH_SIZE": 32

"EPSILON_START": 1.0
"EPSILON_FINISH": 0.1
"EPSILON_ANNEAL_TIME": 1e6
"MAX_GRAD_NORM": 10
"TARGET_UPDATE_INTERVAL": 200 
"LR": 0.005
"LR_LINEAR_DECAY": FALSE
"EPS_ADAM": 0.00001
"TD_LAMBDA_LOSS": TRUE
"TD_LAMBDA": 0.6
"GAMMA": 0.99

hydra/output_subdir: null
hydra/hydra_logging: disabled
hydra/job_logging: disabled


defaults:
- _self_
- env: overcooked.yaml
- user: wilka.yaml
- debug: default.yaml
