# WANDB PARAMS
"PROJECT": "keyroom"
"ENV_NAME": "keyroom"

# RUN PARAMS
"NUM_ENVS": 32
"NUM_STEPS": 128
"EVAL_EPISODES": 100

"TOTAL_TIMESTEPS": 10e6

# ALGO PARAMS
"LEARNING_STARTS": 10_000
"BUFFER_SIZE": 50_000
"BUFFER_BATCH_SIZE": 32
"TARGET_UPDATE_INTERVAL": 500

"EPSILON_START": 1.0
"EPSILON_FINISH": 0.05

"EPSILON_ANNEAL_TIME": 1e6