"ALG": 'alphazero'

# EXPERIMENT PARAMS
"NUM_SEEDS": 1
"SEED": 1

# loggging
"MAX_EPISODE_LOG_LEN": 40


# RUN PARAMS
"TOTAL_TIMESTEPS": 2e6
"NUM_ENVS": 32
"EVAL_STEPS": 100
"EVAL_EPISODES": 100
"LEARNER_LOG_PERIOD": 500
"LEARNER_EXTRA_LOG_PERIOD": 0
"EVAL_LOG_PERIOD": 25
"EVAL_LOG_PERIOD_ACTOR": 0
"GRADIENT_LOG_PERIOD": 5_000

# NEURAL NET PARAMS
"AGENT_HIDDEN_DIM": 32
"NUM_EMBED_LAYERS": 0
"NUM_GRID_LAYERS": 1
"NUM_ENCODER_LAYERS": 2
"GRID_HIDDEN": 256
"ENCODER_INIT": 'word_init'
"AGENT_RNN_DIM": 256

# MCTS PARAMS
#"MAX_SIM_DEPTH": 100
"NUM_SIMULATIONS": 4
"GUMBEL_SCALE": 1.0
"NUM_BINS": 101
"MAX_VALUE": 10

# ALGO PARAMS
"BUFFER_SIZE": 50_000
"BUFFER_BATCH_SIZE": 32
"SAMPLE_LENGTH": 40
"LEARNING_STARTS": 10_000
"TRAINING_INTERVAL": 1


"MAX_GRAD_NORM": 80
"TARGET_UPDATE_INTERVAL": 1_000
"LR": 0.001
"LR_LINEAR_DECAY": FALSE
"EPS_ADAM": 0.00001
"GAMMA": 0.99

